version: '3'
services:

  web:
    build: .
    command: >
      sh -c "npm install && npx sequelize-cli db:migrate:undo:all && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - metabase
      - db
    #network_mode: "host" #Comment this line if using a if using a Windows/macOS host host
    environment:
      DB_HOST:  host.docker.internal # IMPORTANT: Change this to "host.docker.internal" if using a Windows/macOS host
      DB_PW: ${DB_PW}
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT:-5432}

  metabase:
    image: metabase/metabase
    ports:
      - "5000:3000"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT:-5432}:5432"


